/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package ipamexternalresourceverificationtoken

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/crossplane-contrib/provider-aws/apis/ec2/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeIpamExternalResourceVerificationTokensInput returns input for read
// operation.
func GenerateDescribeIpamExternalResourceVerificationTokensInput(cr *svcapitypes.IPAMExternalResourceVerificationToken) *svcsdk.DescribeIpamExternalResourceVerificationTokensInput {
	res := &svcsdk.DescribeIpamExternalResourceVerificationTokensInput{}

	if cr.Spec.ForProvider.DryRun != nil {
		res.SetDryRun(*cr.Spec.ForProvider.DryRun)
	}
	if cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID != nil {
		f2 := []*string{}
		f2 = append(f2, cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID)
		res.SetIpamExternalResourceVerificationTokenIds(f2)
	}

	return res
}

// GenerateIPAMExternalResourceVerificationToken returns the current state in the form of *svcapitypes.IPAMExternalResourceVerificationToken.
func GenerateIPAMExternalResourceVerificationToken(resp *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput) *svcapitypes.IPAMExternalResourceVerificationToken {
	cr := &svcapitypes.IPAMExternalResourceVerificationToken{}

	found := false
	for _, elem := range resp.IpamExternalResourceVerificationTokens {
		if elem.IpamArn != nil {
			cr.Status.AtProvider.IPAMARN = elem.IpamArn
		} else {
			cr.Status.AtProvider.IPAMARN = nil
		}
		if elem.IpamExternalResourceVerificationTokenArn != nil {
			cr.Status.AtProvider.IPAMExternalResourceVerificationTokenARN = elem.IpamExternalResourceVerificationTokenArn
		} else {
			cr.Status.AtProvider.IPAMExternalResourceVerificationTokenARN = nil
		}
		if elem.IpamExternalResourceVerificationTokenId != nil {
			cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID = elem.IpamExternalResourceVerificationTokenId
		} else {
			cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID = nil
		}
		if elem.IpamId != nil {
			cr.Spec.ForProvider.IPAMID = elem.IpamId
		} else {
			cr.Spec.ForProvider.IPAMID = nil
		}
		if elem.IpamRegion != nil {
			cr.Status.AtProvider.IPAMRegion = elem.IpamRegion
		} else {
			cr.Status.AtProvider.IPAMRegion = nil
		}
		if elem.NotAfter != nil {
			cr.Status.AtProvider.NotAfter = &metav1.Time{*elem.NotAfter}
		} else {
			cr.Status.AtProvider.NotAfter = nil
		}
		if elem.State != nil {
			cr.Status.AtProvider.State = elem.State
		} else {
			cr.Status.AtProvider.State = nil
		}
		if elem.Status != nil {
			cr.Status.AtProvider.Status = elem.Status
		} else {
			cr.Status.AtProvider.Status = nil
		}
		if elem.Tags != nil {
			f8 := []*svcapitypes.Tag{}
			for _, f8iter := range elem.Tags {
				f8elem := &svcapitypes.Tag{}
				if f8iter.Key != nil {
					f8elem.Key = f8iter.Key
				}
				if f8iter.Value != nil {
					f8elem.Value = f8iter.Value
				}
				f8 = append(f8, f8elem)
			}
			cr.Status.AtProvider.Tags = f8
		} else {
			cr.Status.AtProvider.Tags = nil
		}
		if elem.TokenName != nil {
			cr.Status.AtProvider.TokenName = elem.TokenName
		} else {
			cr.Status.AtProvider.TokenName = nil
		}
		if elem.TokenValue != nil {
			cr.Status.AtProvider.TokenValue = elem.TokenValue
		} else {
			cr.Status.AtProvider.TokenValue = nil
		}
		found = true
		break
	}
	if !found {
		return cr
	}

	return cr
}

// GenerateCreateIpamExternalResourceVerificationTokenInput returns a create input.
func GenerateCreateIpamExternalResourceVerificationTokenInput(cr *svcapitypes.IPAMExternalResourceVerificationToken) *svcsdk.CreateIpamExternalResourceVerificationTokenInput {
	res := &svcsdk.CreateIpamExternalResourceVerificationTokenInput{}

	if cr.Spec.ForProvider.ClientToken != nil {
		res.SetClientToken(*cr.Spec.ForProvider.ClientToken)
	}
	if cr.Spec.ForProvider.DryRun != nil {
		res.SetDryRun(*cr.Spec.ForProvider.DryRun)
	}
	if cr.Spec.ForProvider.IPAMID != nil {
		res.SetIpamId(*cr.Spec.ForProvider.IPAMID)
	}
	if cr.Spec.ForProvider.TagSpecifications != nil {
		f3 := []*svcsdk.TagSpecification{}
		for _, f3iter := range cr.Spec.ForProvider.TagSpecifications {
			f3elem := &svcsdk.TagSpecification{}
			if f3iter.ResourceType != nil {
				f3elem.SetResourceType(*f3iter.ResourceType)
			}
			if f3iter.Tags != nil {
				f3elemf1 := []*svcsdk.Tag{}
				for _, f3elemf1iter := range f3iter.Tags {
					f3elemf1elem := &svcsdk.Tag{}
					if f3elemf1iter.Key != nil {
						f3elemf1elem.SetKey(*f3elemf1iter.Key)
					}
					if f3elemf1iter.Value != nil {
						f3elemf1elem.SetValue(*f3elemf1iter.Value)
					}
					f3elemf1 = append(f3elemf1, f3elemf1elem)
				}
				f3elem.SetTags(f3elemf1)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTagSpecifications(f3)
	}

	return res
}

// GenerateDeleteIpamExternalResourceVerificationTokenInput returns a deletion input.
func GenerateDeleteIpamExternalResourceVerificationTokenInput(cr *svcapitypes.IPAMExternalResourceVerificationToken) *svcsdk.DeleteIpamExternalResourceVerificationTokenInput {
	res := &svcsdk.DeleteIpamExternalResourceVerificationTokenInput{}

	if cr.Spec.ForProvider.DryRun != nil {
		res.SetDryRun(*cr.Spec.ForProvider.DryRun)
	}
	if cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID != nil {
		res.SetIpamExternalResourceVerificationTokenId(*cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
