/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package ipamexternalresourceverificationtoken

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/ec2"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	svcsdkapi "github.com/aws/aws-sdk-go/service/ec2/ec2iface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane-contrib/provider-aws/apis/ec2/v1alpha1"
	connectaws "github.com/crossplane-contrib/provider-aws/pkg/utils/connect/aws"
	errorutils "github.com/crossplane-contrib/provider-aws/pkg/utils/errors"
)

const (
	errUnexpectedObject = "managed resource is not an IPAMExternalResourceVerificationToken resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create IPAMExternalResourceVerificationToken in AWS"
	errUpdate        = "cannot update IPAMExternalResourceVerificationToken in AWS"
	errDescribe      = "failed to describe IPAMExternalResourceVerificationToken"
	errDelete        = "failed to delete IPAMExternalResourceVerificationToken"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, cr *svcapitypes.IPAMExternalResourceVerificationToken) (managed.TypedExternalClient[*svcapitypes.IPAMExternalResourceVerificationToken], error) {
	sess, err := connectaws.GetConfigV1(ctx, c.kube, cr, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, cr *svcapitypes.IPAMExternalResourceVerificationToken) (managed.ExternalObservation, error) {
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribeIpamExternalResourceVerificationTokensInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribeIpamExternalResourceVerificationTokensWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, errorutils.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	resp = e.filterList(cr, resp)
	if len(resp.IpamExternalResourceVerificationTokens) == 0 {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateIPAMExternalResourceVerificationToken(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)
	upToDate := true
	diff := ""
	if !meta.WasDeleted(cr) { // There is no need to run isUpToDate if the resource is deleted
		upToDate, diff, err = e.isUpToDate(ctx, cr, resp)
		if err != nil {
			return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
		}
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		Diff:                    diff,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, cr *svcapitypes.IPAMExternalResourceVerificationToken) (managed.ExternalCreation, error) {
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateIpamExternalResourceVerificationTokenInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateIpamExternalResourceVerificationTokenWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, errorutils.Wrap(err, errCreate)
	}

	if resp.IpamExternalResourceVerificationToken.IpamArn != nil {
		cr.Status.AtProvider.IPAMARN = resp.IpamExternalResourceVerificationToken.IpamArn
	} else {
		cr.Status.AtProvider.IPAMARN = nil
	}
	if resp.IpamExternalResourceVerificationToken.IpamExternalResourceVerificationTokenArn != nil {
		cr.Status.AtProvider.IPAMExternalResourceVerificationTokenARN = resp.IpamExternalResourceVerificationToken.IpamExternalResourceVerificationTokenArn
	} else {
		cr.Status.AtProvider.IPAMExternalResourceVerificationTokenARN = nil
	}
	if resp.IpamExternalResourceVerificationToken.IpamExternalResourceVerificationTokenId != nil {
		cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID = resp.IpamExternalResourceVerificationToken.IpamExternalResourceVerificationTokenId
	} else {
		cr.Status.AtProvider.IPAMExternalResourceVerificationTokenID = nil
	}
	if resp.IpamExternalResourceVerificationToken.IpamId != nil {
		cr.Spec.ForProvider.IPAMID = resp.IpamExternalResourceVerificationToken.IpamId
	} else {
		cr.Spec.ForProvider.IPAMID = nil
	}
	if resp.IpamExternalResourceVerificationToken.IpamRegion != nil {
		cr.Status.AtProvider.IPAMRegion = resp.IpamExternalResourceVerificationToken.IpamRegion
	} else {
		cr.Status.AtProvider.IPAMRegion = nil
	}
	if resp.IpamExternalResourceVerificationToken.NotAfter != nil {
		cr.Status.AtProvider.NotAfter = &metav1.Time{*resp.IpamExternalResourceVerificationToken.NotAfter}
	} else {
		cr.Status.AtProvider.NotAfter = nil
	}
	if resp.IpamExternalResourceVerificationToken.State != nil {
		cr.Status.AtProvider.State = resp.IpamExternalResourceVerificationToken.State
	} else {
		cr.Status.AtProvider.State = nil
	}
	if resp.IpamExternalResourceVerificationToken.Status != nil {
		cr.Status.AtProvider.Status = resp.IpamExternalResourceVerificationToken.Status
	} else {
		cr.Status.AtProvider.Status = nil
	}
	if resp.IpamExternalResourceVerificationToken.Tags != nil {
		f8 := []*svcapitypes.Tag{}
		for _, f8iter := range resp.IpamExternalResourceVerificationToken.Tags {
			f8elem := &svcapitypes.Tag{}
			if f8iter.Key != nil {
				f8elem.Key = f8iter.Key
			}
			if f8iter.Value != nil {
				f8elem.Value = f8iter.Value
			}
			f8 = append(f8, f8elem)
		}
		cr.Status.AtProvider.Tags = f8
	} else {
		cr.Status.AtProvider.Tags = nil
	}
	if resp.IpamExternalResourceVerificationToken.TokenName != nil {
		cr.Status.AtProvider.TokenName = resp.IpamExternalResourceVerificationToken.TokenName
	} else {
		cr.Status.AtProvider.TokenName = nil
	}
	if resp.IpamExternalResourceVerificationToken.TokenValue != nil {
		cr.Status.AtProvider.TokenValue = resp.IpamExternalResourceVerificationToken.TokenValue
	} else {
		cr.Status.AtProvider.TokenValue = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, cr *svcapitypes.IPAMExternalResourceVerificationToken) (managed.ExternalUpdate, error) {
	return e.update(ctx, cr)

}

func (e *external) Delete(ctx context.Context, cr *svcapitypes.IPAMExternalResourceVerificationToken) (managed.ExternalDelete, error) {
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteIpamExternalResourceVerificationTokenInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return managed.ExternalDelete{}, errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return managed.ExternalDelete{}, nil
	}
	resp, err := e.client.DeleteIpamExternalResourceVerificationTokenWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, errorutils.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

func (e *external) Disconnect(ctx context.Context) error {
	// Unimplemented, required by newer versions of crossplane-runtime
	return nil
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.EC2API, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		filterList:     nopFilterList,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		update:         nopUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.EC2API
	preObserve     func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DescribeIpamExternalResourceVerificationTokensInput) error
	postObserve    func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	filterList     func(*svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput) *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput
	lateInitialize func(*svcapitypes.IPAMExternalResourceVerificationTokenParameters, *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput) error
	isUpToDate     func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput) (bool, string, error)
	preCreate      func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.CreateIpamExternalResourceVerificationTokenInput) error
	postCreate     func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.CreateIpamExternalResourceVerificationTokenOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DeleteIpamExternalResourceVerificationTokenInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DeleteIpamExternalResourceVerificationTokenOutput, error) (managed.ExternalDelete, error)
	update         func(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DescribeIpamExternalResourceVerificationTokensInput) error {
	return nil
}
func nopPostObserve(_ context.Context, _ *svcapitypes.IPAMExternalResourceVerificationToken, _ *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopFilterList(_ *svcapitypes.IPAMExternalResourceVerificationToken, list *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput) *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput {
	return list
}

func nopLateInitialize(*svcapitypes.IPAMExternalResourceVerificationTokenParameters, *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput) error {
	return nil
}
func alwaysUpToDate(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DescribeIpamExternalResourceVerificationTokensOutput) (bool, string, error) {
	return true, "", nil
}

func nopPreCreate(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.CreateIpamExternalResourceVerificationTokenInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.IPAMExternalResourceVerificationToken, _ *svcsdk.CreateIpamExternalResourceVerificationTokenOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken, *svcsdk.DeleteIpamExternalResourceVerificationTokenInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.IPAMExternalResourceVerificationToken, _ *svcsdk.DeleteIpamExternalResourceVerificationTokenOutput, err error) (managed.ExternalDelete, error) {
	return managed.ExternalDelete{}, err
}
func nopUpdate(context.Context, *svcapitypes.IPAMExternalResourceVerificationToken) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}
