/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// IPAMExternalResourceVerificationTokenParameters defines the desired state of IPAMExternalResourceVerificationToken
type IPAMExternalResourceVerificationTokenParameters struct {
	// Region is which region the IPAMExternalResourceVerificationToken will be created.
	// +kubebuilder:validation:Required
	Region string `json:"region"`
	// A unique, case-sensitive identifier that you provide to ensure the idempotency
	// of the request. For more information, see Ensuring idempotency (https://docs.aws.amazon.com/ec2/latest/devguide/ec2-api-idempotency.html).
	ClientToken *string `json:"clientToken,omitempty"`
	// A check for whether you have the required permissions for the action without
	// actually making the request and provides an error response. If you have the
	// required permissions, the error response is DryRunOperation. Otherwise, it
	// is UnauthorizedOperation.
	DryRun *bool `json:"dryRun,omitempty"`
	// The ID of the IPAM that will create the token.
	// +kubebuilder:validation:Required
	IPAMID *string `json:"ipamID"`
	// Token tags.
	TagSpecifications                                     []*TagSpecification `json:"tagSpecifications,omitempty"`
	CustomIPAMExternalResourceVerificationTokenParameters `json:",inline"`
}

// IPAMExternalResourceVerificationTokenSpec defines the desired state of IPAMExternalResourceVerificationToken
type IPAMExternalResourceVerificationTokenSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       IPAMExternalResourceVerificationTokenParameters `json:"forProvider"`
}

// IPAMExternalResourceVerificationTokenObservation defines the observed state of IPAMExternalResourceVerificationToken
type IPAMExternalResourceVerificationTokenObservation struct {
	// ARN of the IPAM that created the token.
	IPAMARN *string `json:"ipamARN,omitempty"`
	// Token ARN.
	IPAMExternalResourceVerificationTokenARN *string `json:"ipamExternalResourceVerificationTokenARN,omitempty"`
	// The ID of the token.
	IPAMExternalResourceVerificationTokenID *string `json:"ipamExternalResourceVerificationTokenID,omitempty"`
	// Region of the IPAM that created the token.
	IPAMRegion *string `json:"ipamRegion,omitempty"`
	// Token expiration.
	NotAfter *metav1.Time `json:"notAfter,omitempty"`
	// Token state.
	State *string `json:"state,omitempty"`
	// Token status.
	Status *string `json:"status,omitempty"`
	// Token tags.
	Tags []*Tag `json:"tags,omitempty"`
	// Token name.
	TokenName *string `json:"tokenName,omitempty"`
	// Token value.
	TokenValue *string `json:"tokenValue,omitempty"`

	CustomIPAMExternalResourceVerificationTokenObservation `json:",inline"`
}

// IPAMExternalResourceVerificationTokenStatus defines the observed state of IPAMExternalResourceVerificationToken.
type IPAMExternalResourceVerificationTokenStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          IPAMExternalResourceVerificationTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// IPAMExternalResourceVerificationToken is the Schema for the IPAMExternalResourceVerificationTokens API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type IPAMExternalResourceVerificationToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              IPAMExternalResourceVerificationTokenSpec   `json:"spec"`
	Status            IPAMExternalResourceVerificationTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IPAMExternalResourceVerificationTokenList contains a list of IPAMExternalResourceVerificationTokens
type IPAMExternalResourceVerificationTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IPAMExternalResourceVerificationToken `json:"items"`
}

// Repository type metadata.
var (
	IPAMExternalResourceVerificationTokenKind             = "IPAMExternalResourceVerificationToken"
	IPAMExternalResourceVerificationTokenGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IPAMExternalResourceVerificationTokenKind}.String()
	IPAMExternalResourceVerificationTokenKindAPIVersion   = IPAMExternalResourceVerificationTokenKind + "." + GroupVersion.String()
	IPAMExternalResourceVerificationTokenGroupVersionKind = GroupVersion.WithKind(IPAMExternalResourceVerificationTokenKind)
)

func init() {
	SchemeBuilder.Register(&IPAMExternalResourceVerificationToken{}, &IPAMExternalResourceVerificationTokenList{})
}
